name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 20
        uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: "adopt"
      - name: Installed Dependencies
        run: mvn install
      - name: Compile project
        run: mvn compile
      - name: Run Unit Tests
        run: mvn test
      - name: Generate JavaDoc
        run: mvn javadoc:javadoc 